[project]
name = "irispy-noa-client"
version = "0.5.0"
description = "An Iris bot client with first-class Noa extension support"
authors = [{ name = "dolidolih", email = "dolidolih@proton.me" }]
maintainers = [{ name = "entworacy" }]
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
    "requests",
    "websockets",
    "pillow",
    "httpx"
]

[project.urls]
Homepage = "https://github.com/entworacy/irispy-noa-client"
Repository = "https://github.com/entworacy/irispy-noa-client"

[project.scripts]
iris = "iris.cli:main"
